-- Add bd_brief column to leads table
-- Stores the AI-generated 7-section BD Brief (lead_summary, how_money_moves,
-- pain_points, opportunity, real_use_case, discovery_questions, bd_verdict).
-- Generated by /api/ai/bd-brief — designed for 30-60 second scannability.

ALTER TABLE leads ADD COLUMN IF NOT EXISTS bd_brief jsonb;
