// ── Aerpolice Customers — Eitan-Qualified Wallet-Signing Prospects ──
// Imported from "Aerpolice_Eitan_Qualified_Prospects_2026-09-07.xlsx"
// (2026-09-07). Scoped strictly to the current wallet-signing product
// definition (see product_hunting_approach for 'aerpolice'): every row
// here already passed Gate 1 (wallet key) and Gate 2 (irreversible
// on-chain action), except the two explicit "Research needed" rows,
// which are unscored on purpose — do not pitch those until the gates
// are confirmed.
//
// This supersedes the older, broader AERPOLICE_CUSTOMERS list (imported
// 2026-09-02) wherever the two disagree: that list scored IT, security,
// coding, customer-support and finance-ops agents that this workbook's
// approach explicitly excludes (see AERPOLICE_LATER_MONITORING below and
// lib/product-sections.ts's aerpolice defaultApproachPlaceholder).

export interface AerpoliceEitanProspect {
  id: number
  company: string
  domain: string | null
  segment: 'S1 Trading' | 'S2 Treasury' | 'S3 Wallet Infra'
  motion: string
  walletKey: 'Yes' | 'No' | 'Unknown'
  walletEvidence: string
  walletEvidenceUrl: string | null
  irreversible: 'Yes' | 'No' | 'Unknown'
  irreversibleAction: string
  actionEvidenceUrl: string | null
  triggerDate: string | null
  whyNow: string
  triggerEvidenceUrl: string | null
  pastLoss: string
  pastLossUrl: string | null
  currentControls: string
  gapToInvestigate: string
  buyerTarget: string
  contactPath: string
  firstQuestion: string
  walletScore: number
  irreversibleScore: number
  triggerScore: number
  integrationScore: number
  reachabilityScore: number
  evidenceScore: number
  /** null when the row is a "Research needed" hold — both gates are Unknown, so it cannot be scored. */
  totalScore: number | null
  tier: string
  nextAction: string
}

export const AERPOLICE_EITAN_PROSPECTS: AerpoliceEitanProspect[] = [
  { id: 1, company: "Rainmaker", domain: "rainmaker.fun", segment: "S1 Trading", motion: "Direct customer", walletKey: "Yes", walletEvidence: "Agent executes Polymarket entries/exits from each user’s own wallet.", walletEvidenceUrl: "https://rainmaker.fun/how-it-works", irreversible: "Yes", irreversibleAction: "Filled Polymarket order and final market settlement.", actionEvidenceUrl: "https://rainmaker.fun/", triggerDate: "2026-09-06", whyNow: "Live US Open fills and settled outcomes were published through Sep 6.", triggerEvidenceUrl: "https://rainmaker.fun/", pastLoss: "Public record includes losing settled trades (−100%), showing real capital exposure.", pastLossUrl: "https://rainmaker.fun/", currentControls: "User wallet; autonomous execution; user sets stake and turns Auto on.", gapToInvestigate: "Where is the non-bypassable mandate enforced before the wallet signs each order?", buyerTarget: "Founder / CTO", contactPath: "Website + public X; reference a specific Sep 6 settled fill.", firstQuestion: "What is the largest position Backspin can open from a user wallet before anyone on your team notices?", walletScore: 25, irreversibleScore: 20, triggerScore: 20, integrationScore: 15, reachabilityScore: 10, evidenceScore: 5, totalScore: 95, tier: "Tier 1", nextAction: "Contact now; request a 20-minute architecture interview." },
  { id: 2, company: "Bankr", domain: "bankr.bot", segment: "S1 Trading", motion: "Direct customer", walletKey: "Yes", walletEvidence: "Every agent gets a cross-chain wallet and can trade, transfer, launch tokens and manage DeFi positions.", walletEvidenceUrl: "https://docs.bankr.bot/", irreversible: "Yes", irreversibleAction: "On-chain swaps, transfers, limit orders and LP deployment.", actionEvidenceUrl: "https://0x.org/case-studies/bankr", triggerDate: "2026-08-28", whyNow: "Launched natural-language LP for tokenized stocks on Aerodrome.", triggerEvidenceUrl: "https://markets.businessinsider.com/news/currencies/bankr-launches-agent-powered-liquidity-for-tokenized-stocks-on-aerodrome-1036503584", pastLoss: "Reported May incident affected at least 14 wallets and led Bankr to pause transactions.", pastLossUrl: "https://www.tradingview.com/news/cointelegraph%3Afb3b7fdb2094b%3A0-bankr-temporarily-disables-transactions-after-14-wallets-hacked/", currentControls: "Production agent wallets; 0x routing; user-confirmed execution also appears in public product text.", gapToInvestigate: "Whether agent mandate is enforced at the signing boundary for every skill and chain.", buyerTarget: "Founder / CTO / Security lead", contactPath: "Founder/engineering team on X and LinkedIn; lead with incident lessons + Aug expansion.", firstQuestion: "After the May wallet incident, what changed at the final signing boundary—not just in app permissions?", walletScore: 25, irreversibleScore: 20, triggerScore: 19, integrationScore: 15, reachabilityScore: 8, evidenceScore: 5, totalScore: 92, tier: "Tier 1", nextAction: "Contact now; highest-value problem interview." },
  { id: 3, company: "Senpi", domain: "senpi.ai", segment: "S1 Trading", motion: "Direct customer", walletKey: "Yes", walletEvidence: "Non-custodial Agent Wallets authorize Senpi to execute Hyperliquid trades.", walletEvidenceUrl: "https://senpi.ai/terms", irreversible: "Yes", irreversibleAction: "Live Hyperliquid orders and positions; terms state blockchain transactions are final and irreversible.", actionEvidenceUrl: "https://senpi.ai/terms", triggerDate: "2026-07-06", whyNow: "Consumer app update and ongoing live autonomous trading; product reports real-capital experiments.", triggerEvidenceUrl: "https://play.google.com/store/apps/details?id=app.senpi.ai", pastLoss: "Ran 43–44 autonomous agents with real capital and published operational lessons.", pastLossUrl: "https://resources.senpi.ai/blog/running-43-autonomous-hyperliquid-agents", currentControls: "Non-custodial delegated permissions; modular trading skills; 24/7 execution.", gapToInvestigate: "Exact key custody and whether strategy intent is cryptographically bound to each signed order.", buyerTarget: "Jason Goldberg / CTO / Security owner", contactPath: "Direct founder LinkedIn/X and public GitHub maintainers.", firstQuestion: "Across your real-capital agent runs, what was the largest unintended position or near-miss before a human caught it?", walletScore: 25, irreversibleScore: 20, triggerScore: 18, integrationScore: 14, reachabilityScore: 9, evidenceScore: 5, totalScore: 91, tier: "Tier 1", nextAction: "Contact now; ask for a 20-minute lessons-learned call." },
  { id: 4, company: "Polystrat (Valory / Olas)", domain: "pearl.you", segment: "S1 Trading", motion: "Direct customer", walletKey: "Yes", walletEvidence: "Agent key signs for a user-owned Safe smart account.", walletEvidenceUrl: "https://olas.network/blog/q2-2026", irreversible: "Yes", irreversibleAction: "Autonomous Polymarket orders; 22k+ trades publicly reported.", actionEvidenceUrl: "https://www.pearl.you/polystrat", triggerDate: "2026-06-30", whyNow: "Olas disclosed a wallet architecture change that paused new Polystrat agents before remediation.", triggerEvidenceUrl: "https://olas.network/blog/q2-2026", pastLoss: "Polymarket wallet change broke Safe-based self-custody and paused new agent creation.", pastLossUrl: "https://olas.network/blog/q2-2026", currentControls: "Safe smart account, local agent, finite-state-machine constraints.", gapToInvestigate: "Whether a compromised agent key can sign an order outside the chosen strategy but inside broad Safe permissions.", buyerTarget: "Valory founder / Pearl product lead / CTO", contactPath: "Olas forum, Discord and Valory leadership; cite their own Q2 retrospective.", firstQuestion: "During the wallet migration, what was the hardest failure mode to contain without stopping users’ agents?", walletScore: 25, irreversibleScore: 20, triggerScore: 18, integrationScore: 13, reachabilityScore: 8, evidenceScore: 5, totalScore: 89, tier: "Tier 1", nextAction: "Contact now; position as a technical learning interview." },
  { id: 5, company: "Wallet V", domain: "walletv.io", segment: "S1 Trading", motion: "Direct customer", walletKey: "Yes", walletEvidence: "Self-custodial wallet; AI models execute strategies 24/7.", walletEvidenceUrl: "https://apps.apple.com/hk/app/wallet-v-create-ai-agents/id6743709480?l=en-GB", irreversible: "Yes", irreversibleAction: "Orders on Hyperliquid, Aster DEX and Polymarket.", actionEvidenceUrl: "https://walletv.io/", triggerDate: "2026-08-20", whyNow: "Android listing updated with live decentralized-platform execution across three venues.", triggerEvidenceUrl: "https://play.google.com/store/apps/details?id=prod.walletv.virgo", pastLoss: "No public incident found; public performance makes realized losses observable.", pastLossUrl: null, currentControls: "Self-custody plus user-defined pairs, amounts and risk settings.", gapToInvestigate: "Whether those limits are enforced by the wallet signer or only by application logic.", buyerTarget: "Founder / CTO", contactPath: "Website community/Telegram and app-publisher contacts.", firstQuestion: "What is the largest trade an active Wallet V agent can place before the user sees an alert?", walletScore: 25, irreversibleScore: 20, triggerScore: 18, integrationScore: 12, reachabilityScore: 8, evidenceScore: 4, totalScore: 87, tier: "Tier 1", nextAction: "Contact now; small team and direct product fit." },
  { id: 6, company: "Almanak", domain: "almanak.co", segment: "S1 Trading", motion: "Direct customer / learning", walletKey: "Yes", walletEvidence: "AI-agent EOA or Safe/Zodiac wallet signs autonomous strategy transactions.", walletEvidenceUrl: "https://almanak.co/almanak-terms-and-conditions-2026.pdf", irreversible: "Yes", irreversibleAction: "Autonomous DeFi trades, LP moves and strategy transactions.", actionEvidenceUrl: "https://platform.docs.almanak.co/workflow.html", triggerDate: "2026-03-31", whyNow: "2026 platform terms and production docs formalized autonomous wallet/signing roles.", triggerEvidenceUrl: "https://almanak.co/almanak-terms-and-conditions-2026.pdf", pastLoss: "No public loss found; platform already includes stuck detection, canaries and emergency controls.", pastLossUrl: "https://sdk.docs.almanak.co/index.html", currentControls: "Safe, Zodiac scoped permissions, simulations and monitoring.", gapToInvestigate: "Whether AERpolice adds anything beyond Almanak’s existing policy-enforced stack.", buyerTarget: "Founder / CTO / Protocol security", contactPath: "Public team, docs and GitHub; approach as peer architecture review.", firstQuestion: "Which real deployment caused you to tighten an agent permission or emergency control?", walletScore: 25, irreversibleScore: 20, triggerScore: 14, integrationScore: 14, reachabilityScore: 8, evidenceScore: 5, totalScore: 86, tier: "Tier 1", nextAction: "Interview first; do not pitch until a residual gap is confirmed." },
  { id: 7, company: "Griffain", domain: "griffain.com", segment: "S1 Trading", motion: "Direct customer", walletKey: "Yes", walletEvidence: "Users unlock a wallet to grant agents permission to sign and send transactions.", walletEvidenceUrl: "https://griffain.com/docs/wallets", irreversible: "Yes", irreversibleAction: "Swaps, token transfers and DeFi executions.", actionEvidenceUrl: "https://griffain.com/docs/getting-started", triggerDate: "2026-06-06", whyNow: "Recent ecosystem coverage highlighted autonomous on-chain agent deployment.", triggerEvidenceUrl: "https://web3.bitget.com/crypto-news/griffin-ai-ignites-the-ai-agent-narrative-what-traders-need-to-know", pastLoss: "No substantiated public loss found.", pastLossUrl: null, currentControls: "Wallet unlock/lock model; exact signer isolation not public.", gapToInvestigate: "Whether mandate constraints persist at signing time after wallet unlock.", buyerTarget: "Founder / CTO", contactPath: "Discord/X and public docs maintainers.", firstQuestion: "Once a user unlocks an agent wallet, what is the largest transaction the agent can sign before another check occurs?", walletScore: 25, irreversibleScore: 20, triggerScore: 12, integrationScore: 13, reachabilityScore: 9, evidenceScore: 4, totalScore: 83, tier: "Tier 1", nextAction: "Contact after one more architecture check; high founder reachability." },
  { id: 8, company: "Cod3x", domain: "cod3x.org", segment: "S1 Trading", motion: "Direct customer", walletKey: "Yes", walletEvidence: "Each agent has a dedicated smart wallet that users fund.", walletEvidenceUrl: "https://docs.cod3x.org/introduction/getting-started", irreversible: "Yes", irreversibleAction: "Autonomous DeFi actions and Hyperliquid perpetual trades via Big Tony.", actionEvidenceUrl: "https://x.com/AlloraNetwork/article/2082450138820411619", triggerDate: "2026-07-29", whyNow: "Allora highlighted its live integration powering Cod3x autonomous trading.", triggerEvidenceUrl: "https://x.com/AlloraNetwork/article/2082450138820411619", pastLoss: "No public loss found.", pastLossUrl: null, currentControls: "Dedicated smart wallet; control and policy implementation not fully public.", gapToInvestigate: "Whether wallet-level enforcement can block a trade that violates the owner’s mandate.", buyerTarget: "Founder / CTO", contactPath: "Discord/X and docs contact.", firstQuestion: "What is the largest position Big Tony has opened that surprised the operator after execution?", walletScore: 25, irreversibleScore: 20, triggerScore: 15, integrationScore: 11, reachabilityScore: 7, evidenceScore: 4, totalScore: 82, tier: "Tier 1", nextAction: "Contact; verify live customer capital and key architecture on first call." },
  { id: 9, company: "HyperAgent", domain: "hyperagent.ch", segment: "S1 Trading", motion: "Direct customer", walletKey: "Yes", walletEvidence: "Non-custodial Hyperliquid setup uses trade-only agent permissions tied to a wallet.", walletEvidenceUrl: "https://hyperagent.ch/", irreversible: "Yes", irreversibleAction: "Autonomous Hyperliquid perpetual orders.", actionEvidenceUrl: "https://hyperagent.ch/", triggerDate: "2026-08-01", whyNow: "Founder publicly demonstrated continuing autonomous-agent development; production scale remains to verify.", triggerEvidenceUrl: "https://www.linkedin.com/posts/0xyashjain_building-hyperagent-an-autonomous-trading-activity-7454869713018318848-iiek", pastLoss: "No public loss found; early iterations included testnet execution.", pastLossUrl: "https://www.linkedin.com/posts/0xyashjain_building-hyperagent-an-autonomous-trading-activity-7454869713018318848-iiek", currentControls: "Trade-only permissions and multiple risk gates.", gapToInvestigate: "Confirm whether today’s live flow uses a private API-wallet key and real customer capital.", buyerTarget: "Founder / CTO", contactPath: "Direct founder LinkedIn; very small team.", firstQuestion: "What is the largest live position the agent can open under its current trade-only mandate?", walletScore: 22, irreversibleScore: 20, triggerScore: 14, integrationScore: 10, reachabilityScore: 9, evidenceScore: 3, totalScore: 78, tier: "Tier 1", nextAction: "Fast interview target; qualify production status in first five minutes." },
  { id: 10, company: "Hey Anon Launchpad", domain: "heyanon.ai", segment: "S1 Trading", motion: "Research needed", walletKey: "Unknown", walletEvidence: "Launchpad promises guaranteed on-chain execution, but public key custody is not explicit.", walletEvidenceUrl: "https://launchpad.heyanon.ai/registry", irreversible: "Yes", irreversibleAction: "Agent-defined on-chain token and trading behaviors.", actionEvidenceUrl: "https://forum.heyanon.ai/t/rfc-5-hey-anon-dao-ai-agent-launchpad-applications/132", triggerDate: "2026-04-10", whyNow: "DAO reviewed an autonomous multi-chain copy-trading/sniping agent proposal.", triggerEvidenceUrl: "https://forum.heyanon.ai/t/rfc-5-hey-anon-dao-ai-agent-launchpad-applications/132", pastLoss: "No verified loss found.", pastLossUrl: null, currentControls: "On-chain execution layer; key owner/controller unknown.", gapToInvestigate: "Does an AI agent possess or invoke a wallet-signing key without human confirmation?", buyerTarget: "Founder / CTO / DAO proposer", contactPath: "Public forum reply or proposer DM.", firstQuestion: "Which deployed agent currently signs trades without a human confirmation, and how much capital has it controlled?", walletScore: 0, irreversibleScore: 0, triggerScore: 0, integrationScore: 0, reachabilityScore: 0, evidenceScore: 0, totalScore: null, tier: "Research hold", nextAction: "Do not pitch; verify wallet-key gate first." },
  { id: 11, company: "Giza", domain: "gizatech.xyz", segment: "S2 Treasury", motion: "Direct customer", walletKey: "Yes", walletEvidence: "Agents delegate execution through smart-account infrastructure.", walletEvidenceUrl: "https://docs.gizaprotocol.ai/introduction/agents", irreversible: "Yes", irreversibleAction: "Autonomous DeFi rebalancing and capital redeployment.", actionEvidenceUrl: "https://www.gizatech.xyz/", triggerDate: "2026-06-06", whyNow: "Giza returned legacy ARMA/Pulse funds to EOAs during migration to a unified agent.", triggerEvidenceUrl: "https://cryptobriefing.com/giza-tech-returns-arma-pulse-funds/", pastLoss: "Legacy-product migration returned user funds and required users to move to the unified agent.", pastLossUrl: "https://x.com/gizatechxyz", currentControls: "Smart accounts, non-custodial sovereignty, auditable agent actions.", gapToInvestigate: "Whether mandate enforcement is cryptographically tied to every signature across the new unified agent.", buyerTarget: "Founder / CTO / Protocol security", contactPath: "Public founders and active X/Discord; reference migration, not fear.", firstQuestion: "During the ARMA/Pulse migration, what wallet-control issue consumed the most engineering time?", walletScore: 25, irreversibleScore: 20, triggerScore: 18, integrationScore: 15, reachabilityScore: 9, evidenceScore: 5, totalScore: 92, tier: "Tier 1", nextAction: "Contact now; strong scale plus migration trigger." },
  { id: 12, company: "Freysa", domain: "freysa.ai", segment: "S2 Treasury", motion: "Direct customer / design partner", walletKey: "Yes", walletEvidence: "Sovereign agent controls a wallet/treasury and can approve transfers.", walletEvidenceUrl: "https://www.freysa.ai/act-i/faq", irreversible: "Yes", irreversibleAction: "On-chain treasury transfer.", actionEvidenceUrl: "https://freysa.ai/", triggerDate: "2024-11-29", whyNow: "Historical but uniquely material evidence: an agent was persuaded to transfer the 13.19 ETH prize pool.", triggerEvidenceUrl: "https://oecd.ai/en/incidents/2024-11-29-2e31", pastLoss: "Agent transferred approximately $47,000 after adversarial prompting; this was an intentional game, not a hidden exploit.", pastLossUrl: "https://x.com/jarrodwatts/status/1862299845710757980", currentControls: "Sovereign-agent stack and trusted execution positioning.", gapToInvestigate: "What new signing boundary was implemented after Act I, and is there a residual integration use case?", buyerTarget: "Founder / CTO / Research lead", contactPath: "Direct team/X; request a lessons-learned interview.", firstQuestion: "After Act I, which control did you decide must sit outside the model before any future treasury signature?", walletScore: 25, irreversibleScore: 20, triggerScore: 20, integrationScore: 13, reachabilityScore: 9, evidenceScore: 5, totalScore: 92, tier: "Tier 1", nextAction: "Contact now for interview; lead with learning, not selling." },
  { id: 13, company: "Olas / Valory", domain: "olas.network", segment: "S2 Treasury", motion: "Direct customer / design partner", walletKey: "Yes", walletEvidence: "Agents use wallets and agent keys; marketplace payments settle on-chain.", walletEvidenceUrl: "https://olas.network/blog/q2-2026", irreversible: "Yes", irreversibleAction: "Prediction trades, DeFi allocations and agent-to-agent payments.", actionEvidenceUrl: "https://olas.network/", triggerDate: "2026-06-30", whyNow: "Q2 update disclosed wallet migration, audit work and a temporary Polystrat pause.", triggerEvidenceUrl: "https://olas.network/blog/q2-2026", pastLoss: "Polymarket wallet change broke the original Safe path; Pearl Mini was later sunset due store policy.", pastLossUrl: "https://olas.network/blog/pearl-mini-sunset", currentControls: "Safe accounts, agent keys, FSM constraints and public security work.", gapToInvestigate: "Residual risk between agent reasoning and its permitted signing surface.", buyerTarget: "Valory CEO / CTO / Pearl lead", contactPath: "Forum, Discord and Valory leadership.", firstQuestion: "Across 20M+ agent transactions, which near-miss most changed how you scope an agent key?", walletScore: 25, irreversibleScore: 20, triggerScore: 18, integrationScore: 13, reachabilityScore: 8, evidenceScore: 5, totalScore: 89, tier: "Tier 1", nextAction: "Contact as a design-partner interview; avoid generic pitch." },
  { id: 14, company: "Brahma", domain: "brahma.fi", segment: "S2 Treasury", motion: "Direct customer / integration", walletKey: "Yes", walletEvidence: "Delegated agents trigger transactions from dedicated Safe smart accounts.", walletEvidenceUrl: "https://docs.brahma.fi/brahma-agents-or-built-with-console-kit/morpho-agent", irreversible: "Yes", irreversibleAction: "Morpho allocations, DCA/TWAP and batched DeFi transactions.", actionEvidenceUrl: "https://docs.brahma.fi/brahma-accounts/strategies-and-agents/automation-and-agents/twap-or-dca-automation", triggerDate: "2026-03-18", whyNow: "Brahma published a Safe-account migration workflow after product/account changes.", triggerEvidenceUrl: "https://docs.brahma.fi/", pastLoss: "Account migration required transaction generation and execution.", pastLossUrl: "https://docs.brahma.fi/", currentControls: "Safe smart accounts, scoped delegated execution and automation rules.", gapToInvestigate: "Whether an external mandate signer offers material value beyond existing Console controls.", buyerTarget: "Founder / CTO / ConsoleKit lead", contactPath: "Public docs and founder X/LinkedIn.", firstQuestion: "What real automation failure or near-miss caused you to narrow an agent’s delegated permissions?", walletScore: 25, irreversibleScore: 20, triggerScore: 14, integrationScore: 14, reachabilityScore: 8, evidenceScore: 5, totalScore: 86, tier: "Tier 1", nextAction: "Interview first; likely complement or integration rather than replacement." },
  { id: 15, company: "Wayfinder", domain: "wayfinder.ai", segment: "S2 Treasury", motion: "Direct customer", walletKey: "Yes", walletEvidence: "Shells control Web3 wallets and request signatures from associated private keys.", walletEvidenceUrl: "https://paper.wayfinder.ai/wayfinder_paper_v1.pdf", irreversible: "Yes", irreversibleAction: "Cross-chain trades, perps, predictions and DeFi actions.", actionEvidenceUrl: "https://x.com/AIWayfinder/article/2062254985874739407", triggerDate: "2026-06-03", whyNow: "Wayfinder launched v2 with cross-chain autonomous workflows for perps, predictions, tokens and DeFi.", triggerEvidenceUrl: "https://x.com/AIWayfinder/article/2062254985874739407", pastLoss: "No verified public loss found.", pastLossUrl: null, currentControls: "Dedicated Web3 wallets associated with Shells; exact key custody and mandate enforcement unknown.", gapToInvestigate: "Can signing be withheld independently if the Shell’s reasoning deviates from the owner’s mandate?", buyerTarget: "Founder / CTO / Wallet infrastructure lead", contactPath: "Public X/Discord and team profiles.", firstQuestion: "Since v2 launched, what was the largest on-chain action a Shell took before a human reviewed it?", walletScore: 25, irreversibleScore: 20, triggerScore: 16, integrationScore: 13, reachabilityScore: 8, evidenceScore: 4, totalScore: 86, tier: "Tier 1", nextAction: "Contact; strong direct fit and manageable company size." },
  { id: 16, company: "Mode Network", domain: "mode.network", segment: "S2 Treasury", motion: "Direct customer / ecosystem operator", walletKey: "Yes", walletEvidence: "Official agent quickstart uses a WALLET_PRIVATE_KEY; live ecosystem includes trading/yield agents.", walletEvidenceUrl: "https://docs.mode.network/ai-agents/tutorials/quickstart", irreversible: "Yes", irreversibleAction: "On-chain trades, yield allocation and contract transactions.", actionEvidenceUrl: "https://www.mode.network/", triggerDate: "2026-09-02", whyNow: "Mode’s broader admin ownership transition creates an active security-review window, while trading agents remain live.", triggerEvidenceUrl: "https://gov.optimism.io/t/maintenance-upgrade-proposal-mode-metal-zora-and-dust-ownership-transfer-to-conduit/10838", pastLoss: "No agent loss verified; raw-private-key quickstart is a concrete exposure to discuss.", pastLossUrl: "https://docs.mode.network/ai-agents/tutorials/quickstart", currentControls: "Example raw private key plus ecosystem-specific agent tooling.", gapToInvestigate: "Whether production agents use stronger isolated signing than the public quickstart.", buyerTarget: "CTO / Head of AI / Security lead", contactPath: "Governance forum and public team channels.", firstQuestion: "What is the largest amount a production Mode agent can move today before a human notices?", walletScore: 25, irreversibleScore: 20, triggerScore: 20, integrationScore: 13, reachabilityScore: 7, evidenceScore: 5, totalScore: 90, tier: "Tier 1", nextAction: "Contact now; route contract-admin discussion separately to AERSeal." },
  { id: 17, company: "aarna", domain: "aarna.ai", segment: "S2 Treasury", motion: "Direct customer", walletKey: "Yes", walletEvidence: "Execution Agent carries out user-authorized on-chain deposits, withdrawals and strategy actions.", walletEvidenceUrl: "https://docs.aarna.ai/aarna-agentic-engine/atars", irreversible: "Yes", irreversibleAction: "Vault deposits, withdrawals and autonomous capital reallocation.", actionEvidenceUrl: "https://docs.aarna.ai/aarna-agentic-engine/atars/atvptmax/working-of-atars-atvptmax", triggerDate: "2026-02-06", whyNow: "aTARS documentation formalized the autonomous execution layer for tokenized vault strategies.", triggerEvidenceUrl: "https://docs.aarna.ai/aarna-agentic-engine/atars", pastLoss: "No verified public loss found.", pastLossUrl: null, currentControls: "Vault contracts plus autonomous execution agent; signer/key topology not public.", gapToInvestigate: "Whether the execution mandate can be enforced at the private-key/signing layer.", buyerTarget: "Founder / CTO / Protocol lead", contactPath: "Docs contact, Telegram/Discord and founder LinkedIn.", firstQuestion: "What is the largest rebalance the execution agent has completed without a human reviewing the final transaction?", walletScore: 25, irreversibleScore: 20, triggerScore: 12, integrationScore: 13, reachabilityScore: 9, evidenceScore: 4, totalScore: 83, tier: "Tier 1", nextAction: "Contact; first verify current live TVL and signer architecture." },
  { id: 18, company: "Theoriq", domain: "theoriq.ai", segment: "S2 Treasury", motion: "Direct customer", walletKey: "Yes", walletEvidence: "AI agent swarms execute and rebalance live on-chain yield vaults.", walletEvidenceUrl: "https://www.theoriq.ai/blog/theoriq-alphavault-ai-eth-ethereum-thq-token-vault-defi-crypto", irreversible: "Yes", irreversibleAction: "Vault-of-vault reallocations and tokenized-gold yield deployment.", actionEvidenceUrl: "https://www.theoriq.ai/blog/theoriq-gold-vault-tokenized-rwa-yield-xaut", triggerDate: "2026-08-18", whyNow: "Joined WisdomTree Connect sandbox while expanding on-chain RWA distribution.", triggerEvidenceUrl: "https://www.theoriq.ai/blog", pastLoss: "May strategic refocus discontinued AlphaChat/AlphaHub to concentrate on RWA vaults.", pastLossUrl: "https://www.theoriq.ai/blog/a-new-chapter-at-theoriq", currentControls: "Defined vault constraints and agent-assisted execution; signing topology unknown.", gapToInvestigate: "Is the final vault signature independently bound to strategy constraints and change control?", buyerTarget: "Founder / CTO / Head of Quant / Security", contactPath: "Public blog, Discord and founder profiles.", firstQuestion: "What allocation change by GoldSwarm created the most internal debate after it had already executed?", walletScore: 25, irreversibleScore: 20, triggerScore: 18, integrationScore: 12, reachabilityScore: 7, evidenceScore: 4, totalScore: 86, tier: "Tier 1", nextAction: "Contact now; RWA sandbox is a timely trigger." },
  { id: 19, company: "Virtuals Protocol", domain: "virtuals.io", segment: "S2 Treasury", motion: "Direct customer / platform", walletKey: "Yes", walletEvidence: "ACP Agent Wallet buys services, receives revenue and supports dedicated trading-agent wallets.", walletEvidenceUrl: "https://whitepaper.virtuals.io/acp/acp-changelogs", irreversible: "Yes", irreversibleAction: "Agent-to-agent payments and autonomous Hyperliquid trades.", actionEvidenceUrl: "https://whitepaper.virtuals.io/about-virtuals/ai-agent-identity-and-banking-layer/agent-console/build-an-ai-trading-agent-on-hyperliquid", triggerDate: "2026-08-11", whyNow: "Published a dedicated Hyperliquid AI-trading-agent workflow with an agent wallet.", triggerEvidenceUrl: "https://whitepaper.virtuals.io/about-virtuals/ai-agent-identity-and-banking-layer/agent-console/build-an-ai-trading-agent-on-hyperliquid", pastLoss: "No verified public loss found.", pastLossUrl: null, currentControls: "Agent wallet with optional controls; precise signer policy boundary varies by deployment.", gapToInvestigate: "Which production agents can sign outside a user-defined economic mandate?", buyerTarget: "Agent Console lead / CTO / Security", contactPath: "Developer community and public team.", firstQuestion: "What is the largest live Agent Wallet balance that can be deployed before an owner is alerted?", walletScore: 25, irreversibleScore: 20, triggerScore: 19, integrationScore: 12, reachabilityScore: 7, evidenceScore: 4, totalScore: 87, tier: "Tier 1", nextAction: "Contact; seek operator story before discussing architecture." },
  { id: 20, company: "Talus Network", domain: "talus.network", segment: "S2 Treasury", motion: "Direct customer / integration", walletKey: "Yes", walletEvidence: "Cubist/CubeSigner hardware-backed transaction signing lets agents transact under wallet policies.", walletEvidenceUrl: "https://blog.talus.network/talus-network-partners-with-cubist-to-build-ai-wallet-automation/", irreversible: "Yes", irreversibleAction: "On-chain transfers, DeFi execution and autonomous value exchange.", actionEvidenceUrl: "https://blog.talus.network/unveiling-nexus-v1-whitepaper-and-devnet-now-live/", triggerDate: "2026-08-26", whyNow: "Talus Protocol v2.0 went live on Sui mainnet with trustworthy on-chain agents.", triggerEvidenceUrl: "https://blog.talus.network/", pastLoss: "No public loss found; existing CubeSigner guardrails create incumbent friction.", pastLossUrl: "https://blog.talus.network/talus-network-partners-with-cubist-to-build-ai-wallet-automation/", currentControls: "Hardware-backed signing and programmable policies from Cubist.", gapToInvestigate: "Whether AERpolice has a differentiated value versus the existing signer/policy stack.", buyerTarget: "Founder / CTO / Nexus lead", contactPath: "Public team, Discord and blog authors.", firstQuestion: "What production incident or near-miss has tested the wallet policies since v2.0 went live?", walletScore: 25, irreversibleScore: 20, triggerScore: 19, integrationScore: 8, reachabilityScore: 7, evidenceScore: 5, totalScore: 84, tier: "Tier 1", nextAction: "Learning interview only; do not pitch without a proven gap." },
  { id: 21, company: "Crossmint", domain: "crossmint.com", segment: "S3 Wallet Infra", motion: "Learning / OEM / possible buyer", walletKey: "Yes", walletEvidence: "Agent wallets hold funds and sign stablecoin/on-chain payments; pluggable signers supported.", walletEvidenceUrl: "https://www.crossmint.com/solutions/agentic-finance", irreversible: "Yes", irreversibleAction: "Stablecoin payment, token transfer and x402 settlement.", actionEvidenceUrl: "https://www.crossmint.com/learn/inside-an-x402-transaction", triggerDate: "2026-08-28", whyNow: "Published an end-to-end live x402 transaction walkthrough and identified remaining ecosystem gaps.", triggerEvidenceUrl: "https://www.crossmint.com/learn/inside-an-x402-transaction", pastLoss: "No public loss found; Crossmint says guardrails/intent and recourse remain ecosystem systems to mature.", pastLossUrl: "https://www.crossmint.com/learn/six-systems-agentic-commerce-needs-to-scale", currentControls: "Smart wallets, signer choice, spending controls and payments orchestration.", gapToInvestigate: "AERpolice differentiation is unproven; call is primarily to learn or identify an OEM boundary.", buyerTarget: "Co-founder / Agentic Finance lead / CTO", contactPath: "Partner form and founder LinkedIn; explicitly request a learning call.", firstQuestion: "Which customer incident has most changed the signing controls you expose for agent wallets?", walletScore: 25, irreversibleScore: 20, triggerScore: 20, integrationScore: 13, reachabilityScore: 8, evidenceScore: 5, totalScore: 91, tier: "Tier 1", nextAction: "Top learning interview; do not open with a replacement pitch." },
  { id: 22, company: "human.tech", domain: "human.tech", segment: "S3 Wallet Infra", motion: "Learning / integration", walletKey: "Yes", walletEvidence: "Agent transacts through a 2PC wallet; full key is split and agent cannot sign alone.", walletEvidenceUrl: "https://docs.human.tech/use-cases-ai-agents", irreversible: "Yes", irreversibleAction: "On-chain agent payments and multi-chain transactions.", actionEvidenceUrl: "https://human.tech/blog/unveiling-wallet-as-a-protocol", triggerDate: "2026-08-24", whyNow: "Launched Wallet Protocol on Ika for dapps and AI agents.", triggerEvidenceUrl: "https://human.tech/blog/unveiling-wallet-as-a-protocol", pastLoss: "No public loss found; product already advertises automation safeguards.", pastLossUrl: "https://docs.human.tech/use-cases-ai-agents", currentControls: "2PC, enclave-enforced privileges, shared human/agent wallet control.", gapToInvestigate: "AERpolice may overlap heavily; determine if there is a complementary mandate/audit role.", buyerTarget: "CTO / Wallet Protocol lead", contactPath: "Direct CTO/founder via launch announcement and LinkedIn.", firstQuestion: "What failure scenario drove you to require the agent never hold the complete signing key?", walletScore: 25, irreversibleScore: 20, triggerScore: 20, integrationScore: 10, reachabilityScore: 10, evidenceScore: 5, totalScore: 90, tier: "Tier 1", nextAction: "Learning interview; likely design partner or integration, not immediate replacement." },
  { id: 23, company: "Skyfire", domain: "skyfire.xyz", segment: "S3 Wallet Infra", motion: "Learning / OEM / possible buyer", walletKey: "Yes", walletEvidence: "Programmatic agent wallets pay in USDC and bind wallet/payment authorization to KYA credentials.", walletEvidenceUrl: "https://skyfire.xyz/product/", irreversible: "Yes", irreversibleAction: "USDC agent payment and stablecoin settlement.", actionEvidenceUrl: "https://skyfire.xyz/overview-ai-agents-and-payments/", triggerDate: "2026-08-01", whyNow: "Published updated authorization architecture describing wallet binding and spend authority.", triggerEvidenceUrl: "https://skyfire.xyz/ai-agent-authorization-flows/", pastLoss: "No public loss found; early materials openly frame agent overspending as the design risk.", pastLossUrl: "https://techcrunch.com/2024/08/21/skyfire-lets-ai-agents-spend-your-money/", currentControls: "Agentic wallet, limits, KYA+pay credentials and human review.", gapToInvestigate: "Whether AERpolice offers any stronger signing guarantee than Skyfire’s current authorization model.", buyerTarget: "Amir Sarhangi / CTO / Product security", contactPath: "Founder LinkedIn/X and contact page.", firstQuestion: "What real payment behavior has forced you to change an agent’s spend policy after launch?", walletScore: 25, irreversibleScore: 20, triggerScore: 18, integrationScore: 10, reachabilityScore: 10, evidenceScore: 5, totalScore: 88, tier: "Tier 1", nextAction: "High-value learning interview; pitch only if a residual gap emerges." },
  { id: 24, company: "t54", domain: "t54.ai", segment: "S3 Wallet Infra", motion: "Learning / integration", walletKey: "Yes", walletEvidence: "XRPL x402 uses payer-signed presigned transactions in XRP/RLUSD.", walletEvidenceUrl: "https://xrpl-x402.t54.ai/", irreversible: "Yes", irreversibleAction: "Final XRPL settlement for x402 services.", actionEvidenceUrl: "https://xrpl.org/docs/agents/agentic-payments-x402", triggerDate: "2026-08-21", whyNow: "Expanded public discussion of multi-rail agent settlement and risk; XRPL reference implementation is live.", triggerEvidenceUrl: "https://www.t54.ai/", pastLoss: "No public loss found; product itself focuses on mandate evidence, underwriting and transaction risk.", pastLossUrl: "https://www.t54.ai/docs/trustline/risk-engine", currentControls: "Invoice binding, presigned payments, risk engine and Verifiable Intent integration.", gapToInvestigate: "Likely overlap; use the call to map boundaries between underwriting, intent evidence and signing custody.", buyerTarget: "Chandler Fang / CTO / Protocol lead", contactPath: "Direct founder LinkedIn/X and docs GitHub.", firstQuestion: "Which live agent payment most challenged your original assumptions about mandate or intent?", walletScore: 25, irreversibleScore: 20, triggerScore: 18, integrationScore: 10, reachabilityScore: 9, evidenceScore: 5, totalScore: 87, tier: "Tier 1", nextAction: "Founder interview now; learning motion, not replacement pitch." },
  { id: 25, company: "Nevermined", domain: "nevermined.ai", segment: "S3 Wallet Infra", motion: "Learning / OEM / possible buyer", walletKey: "Yes", walletEvidence: "Privy-linked agent wallets fund and settle stablecoin payments on-chain.", walletEvidenceUrl: "https://privy.io/blog/building-the-future-of-agentic-payments-with-nevermined", irreversible: "Yes", irreversibleAction: "USDC/EURC agent-to-agent settlement and x402 payments.", actionEvidenceUrl: "https://nevermined.app/", triggerDate: "2026-09-04", whyNow: "Published new agentic-settlement material while expanding payment/monetization infrastructure.", triggerEvidenceUrl: "https://nevermined.ai/blog/best-platforms-agentic-settlements", pastLoss: "No public loss found; latest You.com flow is delegated card and must not be treated as current wallet-key fit.", pastLossUrl: "https://nevermined.ai/blog/youdotcom-nevermined-autonomous-ai-agent-payments", currentControls: "Privy delegation, platform pricing/budget controls and protocol settlement.", gapToInvestigate: "Confirm which live customers actually use on-chain wallet signing rather than cards or internal credits.", buyerTarget: "Founder / CTO / Payments lead", contactPath: "contact@nevermined.ai and founder LinkedIn.", firstQuestion: "In the on-chain payment flow—not card purchases—what is the largest agent spend that can happen before an owner is notified?", walletScore: 25, irreversibleScore: 20, triggerScore: 20, integrationScore: 11, reachabilityScore: 8, evidenceScore: 5, totalScore: 89, tier: "Tier 1", nextAction: "Contact; qualify wallet-settlement share before pitching." },
  { id: 26, company: "Dynamic", domain: "dynamic.xyz", segment: "S3 Wallet Infra", motion: "Learning / integration", walletKey: "Yes", walletEvidence: "Server wallets and delegated access let agents sign on-chain payments without frontend approval.", walletEvidenceUrl: "https://www.dynamic.xyz/use-case/agentic", irreversible: "Yes", irreversibleAction: "Token transfer, smart-contract call and on-chain payment.", actionEvidenceUrl: "https://www.dynamic.xyz/use-case/agentic", triggerDate: "2026-08-15", whyNow: "Current agentic-wallet product page documents autonomous multi-chain operation.", triggerEvidenceUrl: "https://www.dynamic.xyz/use-case/agentic", pastLoss: "No public loss or stalled initiative found.", pastLossUrl: null, currentControls: "Server wallets, delegated access and wallet infrastructure.", gapToInvestigate: "Policy-enforcement depth and signer isolation are not fully described publicly.", buyerTarget: "Agentic product lead / CTO / Security", contactPath: "Founder/product lead LinkedIn and developer Discord.", firstQuestion: "Which customer deployment has pushed your delegated-wallet controls beyond simple scopes?", walletScore: 25, irreversibleScore: 20, triggerScore: 14, integrationScore: 12, reachabilityScore: 8, evidenceScore: 4, totalScore: 83, tier: "Tier 1", nextAction: "Interview; ask about OEM/complement boundaries." },
  { id: 27, company: "Para", domain: "getpara.com", segment: "S3 Wallet Infra", motion: "Learning / integration", walletKey: "Yes", walletEvidence: "ElizaOS agents create/manage EVM wallets and send transactions through Para.", walletEvidenceUrl: "https://docs.getpara.com/v2/walkthroughs/Eliza", irreversible: "Yes", irreversibleAction: "EVM token transfer and smart-contract transaction.", actionEvidenceUrl: "https://docs.getpara.com/v2/walkthroughs/Eliza", triggerDate: "2026-02-27", whyNow: "Published agent identity/wallet design guidance around autonomous trading and payment.", triggerEvidenceUrl: "https://blog.getpara.com/agent-identity-how-agent-wallets-inherit-credentials-in-2026/", pastLoss: "No public loss found.", pastLossUrl: null, currentControls: "Embedded wallets and agent-wallet integrations; key custody/policy model varies by implementation.", gapToInvestigate: "Whether Para wants an external non-bypassable mandate layer or considers this application responsibility.", buyerTarget: "Founder / CTO / Agent-wallet lead", contactPath: "Developer Discord and public team profiles.", firstQuestion: "What is the largest live transfer a Para-powered agent has signed without per-transaction human approval?", walletScore: 25, irreversibleScore: 20, triggerScore: 12, integrationScore: 12, reachabilityScore: 9, evidenceScore: 4, totalScore: 82, tier: "Tier 1", nextAction: "Founder interview; qualify production customer volume." },
  { id: 28, company: "Kite AI", domain: "gokite.ai", segment: "S3 Wallet Infra", motion: "Learning / ecosystem integration", walletKey: "Yes", walletEvidence: "Agent Passport provides funded wallets and signed spending sessions.", walletEvidenceUrl: "https://gokite.ai/", irreversible: "Yes", irreversibleAction: "Stablecoin payments and state-channel settlement anchored on-chain.", actionEvidenceUrl: "https://gokite.ai/kite-whitepaper", triggerDate: "2026-04-30", whyNow: "Kite Chain and Agent Passport launched for autonomous agent payments.", triggerEvidenceUrl: "https://gokite.ai/", pastLoss: "No public loss found; built-in policy controls create overlap.", pastLossUrl: "https://gokite.ai/kite-whitepaper", currentControls: "Agent identity, session keys, programmable governance and state-channel settlement.", gapToInvestigate: "AERpolice differentiation versus Passport controls is unknown.", buyerTarget: "Founder / CTO / Passport lead", contactPath: "Founder/public team X and developer community.", firstQuestion: "What production payment has most stress-tested your session-key and spending-limit design?", walletScore: 25, irreversibleScore: 20, triggerScore: 12, integrationScore: 8, reachabilityScore: 8, evidenceScore: 5, totalScore: 78, tier: "Tier 1", nextAction: "Learning interview only; not a near-term replacement lead." },
  { id: 29, company: "Catena Labs", domain: "catena.com", segment: "S3 Wallet Infra", motion: "Learning / integration", walletKey: "Yes", walletEvidence: "Programmable agent accounts support on-chain stablecoin transactions under deterministic policies.", walletEvidenceUrl: "https://catena.com/", irreversible: "Yes", irreversibleAction: "Stablecoin payment and treasury transaction.", actionEvidenceUrl: "https://a16zcrypto.com/posts/article/investing-in-catena-part-ii/", triggerDate: "2026-05-20", whyNow: "Raised capital and expanded programmable agent accounts across payment rails.", triggerEvidenceUrl: "https://a16zcrypto.com/posts/article/investing-in-catena-part-ii/", pastLoss: "No public loss found; product is itself a governance layer.", pastLossUrl: "https://catena.com/", currentControls: "Deterministic policy layer, agent credentialing and programmable accounts.", gapToInvestigate: "Likely competitor/peer; seek learning or narrow hardware-signing integration only.", buyerTarget: "Founder / CTO / Governance product lead", contactPath: "hello@catena.com and founder network.", firstQuestion: "Which real transaction pattern forced Catena to add or change a deterministic policy?", walletScore: 25, irreversibleScore: 20, triggerScore: 13, integrationScore: 7, reachabilityScore: 7, evidenceScore: 5, totalScore: 77, tier: "Tier 1", nextAction: "Learning call; no product pitch unless hardware-key custody gap is explicit." },
  { id: 30, company: "Openfort", domain: "openfort.io", segment: "S3 Wallet Infra", motion: "Learning / competitor", walletKey: "Yes", walletEvidence: "Agent wallets autonomously sign EVM/Solana transactions within programmable controls.", walletEvidenceUrl: "https://www.openfort.io/solutions/ai-agents", irreversible: "Yes", irreversibleAction: "On-chain trades, transfers and contract calls.", actionEvidenceUrl: "https://www.openfort.io/solutions/ai-agents", triggerDate: "2026-07-18", whyNow: "Published 2026 agent-wallet comparison and actively markets production agent-wallet controls.", triggerEvidenceUrl: "https://www.openfort.io/blog/best-agent-wallets-for-developers", pastLoss: "No public loss found.", pastLossUrl: null, currentControls: "Spend limits, allowlists, policy-gated keys and audit trails.", gapToInvestigate: "Direct competitor; only a learning, interoperability or differentiated hardware-enforcement conversation.", buyerTarget: "Founder / CTO / Security architect", contactPath: "Founder LinkedIn and public developer channels.", firstQuestion: "Which customer failure mode led you to enforce policy at the key rather than in the agent application?", walletScore: 25, irreversibleScore: 20, triggerScore: 17, integrationScore: 5, reachabilityScore: 8, evidenceScore: 5, totalScore: 80, tier: "Tier 1", nextAction: "Learning only; do not count as near-term customer." },
  { id: 31, company: "Sapiom", domain: "sapiom.ai", segment: "S3 Wallet Infra", motion: "Research needed (Eitan-named)", walletKey: "Unknown", walletEvidence: "Public materials confirm production agent spend, but not a sufficiently clear on-chain wallet-signing path.", walletEvidenceUrl: "https://www.sapiom.ai/", irreversible: "Unknown", irreversibleAction: "Most documented activity is service purchasing/runtime cost rather than proven on-chain settlement.", actionEvidenceUrl: "https://www.sapiom.ai/resources/blog/the-next-trillion-agents/", triggerDate: "2026-08-05", whyNow: "Raised $35M Series A and disclosed 270M+ transactions / 100k+ agent runs per day.", triggerEvidenceUrl: "https://www.sapiom.ai/resources/blog/series-a/", pastLoss: "Acquired Fewsats to bring machine-payment rails into the execution layer; exact wallet-key path remains unclear.", pastLossUrl: "https://www.sapiom.ai/resources/blog/", currentControls: "Runtime policy and budget controls; rail mix is not sufficiently public.", gapToInvestigate: "Does any production Sapiom flow let an agent sign an irreversible on-chain transfer with a wallet key?", buyerTarget: "Ilan Zerbib / CTO", contactPath: "partners@sapiom.ai and founder LinkedIn.", firstQuestion: "Which production workflow today ends with an agent-controlled on-chain wallet signature?", walletScore: 0, irreversibleScore: 0, triggerScore: 0, integrationScore: 0, reachabilityScore: 0, evidenceScore: 0, totalScore: null, tier: "Research hold", nextAction: "Do not score or pitch until wallet-key and irreversibility gates are confirmed." },]

export const AERPOLICE_EITAN_SEGMENTS: string[] = ['All', 'S1 Trading', 'S2 Treasury', 'S3 Wallet Infra']

/** Unique companies (an account appearing twice would count once). */
export const AERPOLICE_EITAN_ACCOUNT_COUNT = new Set(AERPOLICE_EITAN_PROSPECTS.map(c => c.company)).size

// ── Later, monitoring & rejected ─────────────────────────────────────
// Intentionally excluded from the current wallet-signing pipeline —
// no wallet key today, a reversible action, or explicitly deferred
// until Aerpolice adds broker/exchange-API-key or fiat-rail support.
// Kept here (not as leads) so nobody re-adds them without re-checking
// the gates first.

export interface AerpoliceLaterMonitoring {
  id: number
  company: string
  bucket: string
  whyExcluded: string
  nextRule: string
}

export const AERPOLICE_LATER_MONITORING: AerpoliceLaterMonitoring[] = [
  { id: 1, company: "Portainer", bucket: "Monitoring — reversible system action", whyExcluded: "No wallet key; infrastructure changes are reversible.", nextRule: "Return only if Aerpolice expands beyond payment signing." },
  { id: 2, company: "PostHog", bucket: "Monitoring — reversible system action", whyExcluded: "No wallet key; product/config changes can be rolled back.", nextRule: "Do not send." },
  { id: 3, company: "Strapi", bucket: "Monitoring — reversible content action", whyExcluded: "No wallet key; content writes/publishing are reversible.", nextRule: "Do not send." },
  { id: 4, company: "Payman", bucket: "Later — API keys & fiat rails", whyExcluded: "Eitan classified for future API/fiat extension.", nextRule: "Revisit after broker/payment API-key support ships." },
  { id: 5, company: "PayOS", bucket: "Later — API keys & fiat rails", whyExcluded: "Eitan classified for future API/fiat extension.", nextRule: "Revisit later." },
  { id: 6, company: "Proxy", bucket: "Later — API keys & fiat rails", whyExcluded: "Eitan classified for future API/fiat extension.", nextRule: "Revisit later." },
  { id: 7, company: "Coinflow", bucket: "Later — API keys & fiat rails", whyExcluded: "Primarily payments API/fiat/card infrastructure for this motion.", nextRule: "Revisit later." },
  { id: 8, company: "Yuno", bucket: "Later — API keys & fiat rails", whyExcluded: "Payment orchestration; no current wallet-key gate.", nextRule: "Revisit later." },
  { id: 9, company: "Paytic", bucket: "Later — API keys & fiat rails", whyExcluded: "Fiat/payment operations rather than on-chain agent key.", nextRule: "Revisit later." },
  { id: 10, company: "Vic.ai", bucket: "Later — API keys & fiat rails", whyExcluded: "AP automation; reversible/fiat flow.", nextRule: "Revisit later." },
  { id: 11, company: "Hyperbots", bucket: "Later — API keys & fiat rails", whyExcluded: "Finance automation without verified on-chain signing.", nextRule: "Revisit later." },
  { id: 12, company: "Phacet", bucket: "Later — API keys & fiat rails", whyExcluded: "No verified agent wallet signature.", nextRule: "Revisit later." },
  { id: 13, company: "Petl", bucket: "Later — API keys & fiat rails", whyExcluded: "No verified agent wallet signature.", nextRule: "Revisit later." },
  { id: 14, company: "Maximor", bucket: "Later — API keys & fiat rails", whyExcluded: "Finance automation without verified on-chain signing.", nextRule: "Revisit later." },
  { id: 15, company: "Hey Savi", bucket: "Dropped", whyExcluded: "Card checkout belongs to card networks; Eitan explicitly dropped it.", nextRule: "Remove from pipeline." },
  { id: 16, company: "Chance AI", bucket: "Research needed", whyExcluded: "Secondary evidence suggests Privy/Polygon wallet execution; primary proof insufficient.", nextRule: "Verify direct wallet/signing docs before scoring." },]
