// ── AERSeal High-Conversion Prospects — 20-account batch ────────────
// Imported verbatim from the "AERSeal — 20 Smaller, Higher-Reach Prospects"
// research workbook (dated 2026-09-02). This is a distinct, smaller batch
// from AERSEAL_CUSTOMERS in aerseal-customers.ts — narrower reach-focused
// targets with full CONFIRMED FACT / INFERENCE / UNKNOWN separation and a
// per-account controller classification, not yet merged into that list.
// Every score is the workbook's computed value — not self-reported.

export interface AersealHighConversionProspect {
  rank: number
  company: string
  segment: string
  chains: string
  triggerDate: string | null
  datedTrigger: string
  privilegedRole: string
  currentController: string
  confirmedFact: string
  inference: string
  unknown: string
  whyNow: string
  likelyBuyer: string
  reachRoute: string
  smartFirstQuestion: string
  structuralSourceUrl: string | null
  triggerSourceUrl: string | null
  /** Sub-scores, workbook's own weights */
  fitScore: number // /30 — AERSeal structural fit
  triggerScore: number // /25 — dated trigger strength
  reachScore: number // /20 — reachability
  consequenceScore: number // /15 — operational/reputational exposure
  evidenceScore: number // /10 — evidence confidence
  lockInPenalty: number // 0–10 — switching-cost penalty
  score: number // 0–100 computed total
  tier: 'Tier 1' | 'Tier 2' | 'Research'
  readiness: string
  outreachPosture: string
}

export const AERSEAL_HIGH_CONVERSION_BATCH_DATE = '2026-09-02'

export const AERSEAL_HIGH_CONVERSION_PROSPECTS: AersealHighConversionProspect[] = [
  {
    rank: 1,
    company: "Monetrix",
    segment: "Synthetic dollar / HyperEVM",
    chains: "HyperEVM",
    triggerDate: "2026-05-26",
    datedTrigger: "Code4rena published the final audit after an Apr\u2013May review. The public scope documents a single UPGRADER across nine proxies and distinct admin, governor, operator and guardian roles.",
    privilegedRole: "UPGRADER for 9 UUPS proxies; DEFAULT_ADMIN; GOVERNOR; instant GUARDIAN pause; trusted OPERATOR.",
    currentController: "Partly confirmed: 24\u201348h timelocks are documented; signer/key architecture behind each role is unknown.",
    confirmedFact: "All user-facing contracts are UUPS-upgradeable. A single UPGRADER can replace nine implementations; roles and delays are documented in the audit repository.",
    inference: "AERSeal may strengthen the signer layer beneath the existing role split and timelocks without changing protocol logic.",
    unknown: "Who holds the role keys, signing threshold, key generation/recovery, and whether the multi-operator policy is cryptographically enforced.",
    whyNow: "The system has just completed an audit and the admin model is still explicit and reviewable; this is the cleanest pre-production architecture conversation in the list.",
    likelyBuyer: "Founder/CTO; smart-contract lead; security lead",
    reachRoute: "Monetrix official X/Discord and GitHub contributors; then LinkedIn to founder or protocol lead.",
    smartFirstQuestion: "Your audit separates DEFAULT_ADMIN, UPGRADER and GUARDIAN with delays. How are the signer keys behind those roles generated, recovered and kept from becoming complete single-device keys?",
    structuralSourceUrl: "https://github.com/code-423n4/2026-04-monetrix",
    triggerSourceUrl: "https://code4rena.com/reports/2026-04-monetrix",
    fitScore: 28,
    triggerScore: 24,
    reachScore: 20,
    consequenceScore: 12,
    evidenceScore: 10,
    lockInPenalty: 1,
    score: 93,
    tier: "Tier 1",
    readiness: "Send now",
    outreachPosture: "Architecture review; acknowledge existing timelocks and role separation.",
  },
  {
    rank: 2,
    company: "Term Finance (Term Labs)",
    segment: "Fixed-rate lending / vaults",
    chains: "Ethereum",
    triggerDate: "2026-08-24",
    datedTrigger: "A governance attack reportedly drained about $8.5M from strategy/meta vaults; the team removed governance permissions and began an investigation.",
    privilegedRole: "Governance/timelock authority over vaults and strategy execution.",
    currentController: "Post-incident controller architecture is changing or unknown.",
    confirmedFact: "Public reporting says the affected authority was governance over vaults; the team reportedly revoked DAO roles after the incident.",
    inference: "AERSeal may be relevant to the redesigned privileged execution layer, but only if the team wants threshold custody beneath governance.",
    unknown: "Final incident facts, remediation plan, new controller, and whether AERSeal fits the future design.",
    whyNow: "This is the most urgent authority-redesign event, but outreach must be empathetic and offer help\u2014not exploit the incident.",
    likelyBuyer: "CTO/security lead; incident-response owner",
    reachRoute: "Official Term Labs channel or warm intro only; avoid public sales replies to incident posts.",
    smartFirstQuestion: "As you redesign the vault governance boundary, would it be useful to compare options for keeping final admin execution threshold-controlled even if governance permissions change?",
    structuralSourceUrl: "https://github.com/term-finance/term-finance-contracts",
    triggerSourceUrl: "https://rekt.news/term-labs-rekt",
    fitScore: 30,
    triggerScore: 25,
    reachScore: 16,
    consequenceScore: 15,
    evidenceScore: 9,
    lockInPenalty: 3,
    score: 92,
    tier: "Tier 1",
    readiness: "Warm/consultative only",
    outreachPosture: "No fear language, no blame, no claim that AERSeal would have prevented the incident.",
  },
  {
    rank: 3,
    company: "TermMax",
    segment: "Fixed-rate lending",
    chains: "Ethereum",
    triggerDate: "2026-08-24",
    datedTrigger: "The Immunefi scope was updated after an Aug 23 ABDK audit and recently added V2 application/token assets.",
    privilegedRole: "Contract upgrade proposals initiated by an admin multisig.",
    currentController: "Confirmed admin multisig; threshold, signer custody and recovery are not public.",
    confirmedFact: "Official docs say the technical team prepares upgrade data and the admin multisig initiates the upgrade proposal.",
    inference: "AERSeal could preserve multisig governance while replacing complete signer keys with threshold-controlled authority.",
    unknown: "Multisig type, threshold, signer concentration, key storage and emergency recovery.",
    whyNow: "Fresh audit and V2 scope changes mean the team is actively touching the contracts and security process this week.",
    likelyBuyer: "CTO; protocol lead; security owner",
    reachRoute: "Official Discord/contact from TermMax docs; LinkedIn to engineering leadership.",
    smartFirstQuestion: "Your upgrade flow already uses an admin multisig\u2014are those signer keys still complete keys per signer, or are they threshold-generated and policy-controlled?",
    structuralSourceUrl: "https://docs.ts.finance/technical-details/contract/contract-upgrade",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/termstructurelabs/information/",
    fitScore: 28,
    triggerScore: 24,
    reachScore: 19,
    consequenceScore: 12,
    evidenceScore: 10,
    lockInPenalty: 2,
    score: 91,
    tier: "Tier 1",
    readiness: "Send now",
    outreachPosture: "Complement the existing multisig; never imply it is weak.",
  },
  {
    rank: 4,
    company: "Money on Chain / RIF on Chain",
    segment: "Stablecoin + governance",
    chains: "Rootstock (EVM)",
    triggerDate: "2026-08-20",
    datedTrigger: "Immunefi updated the program; the team also refreshed an AI-friendly list of governance/oracle issues on Aug 10.",
    privilegedRole: "MOC-token governance controls governance, oracle, fee-flow and supporting contracts; thresholds and delays are explicit security boundaries.",
    currentController: "Governance confirmed; execution signer/custody layer remains unknown.",
    confirmedFact: "The bounty states governance must enforce voting thresholds, staking requirements, delays and execution authorization.",
    inference: "AERSeal may protect the final privileged execution authority beneath governance and oracle administration.",
    unknown: "Whether execution ultimately lands on an EOA, multisig, timelock executor or threshold-controlled signer.",
    whyNow: "Small bounty, open issue workflow and explicit willingness to review AI-assisted security findings suggest an unusually reachable security-conscious team.",
    likelyBuyer: "Protocol maintainer; governance/security lead",
    reachRoute: "Official governance/GitHub issue channels and project community; follow with maintainer LinkedIn.",
    smartFirstQuestion: "After a governance decision passes, what address actually executes changes to oracle and fee-flow contracts, and how are that executor\u2019s signer keys protected?",
    structuralSourceUrl: "https://immunefi.com/bug-bounty/moneyonchain/information/",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/moneyonchain/information/",
    fitScore: 28,
    triggerScore: 22,
    reachScore: 20,
    consequenceScore: 11,
    evidenceScore: 10,
    lockInPenalty: 1,
    score: 90,
    tier: "Tier 1",
    readiness: "Send now",
    outreachPosture: "Lead with their governance-security boundary, not generic key security.",
  },
  {
    rank: 5,
    company: "Intuition",
    segment: "InfoFi protocol + EVM L3",
    chains: "Base + Intuition EVM",
    triggerDate: "2026-08-27",
    datedTrigger: "The Immunefi program was updated after a March Code4rena audit and April mitigation review; current deployment tooling exposes proxy-admin addresses.",
    privilegedRole: "ADMIN has proxy-upgrade and contract-management rights for cross-chain token hub/spoke contracts.",
    currentController: "Admin address and ProxyAdmin contracts are public; operating key architecture is unknown.",
    confirmedFact: "Official deployment toolkit defines ADMIN as the upgrade/management authority and recommends a multisig; production ProxyAdmin addresses are listed.",
    inference: "AERSeal may protect the cross-chain admin authority consistently across Base and Intuition.",
    unknown: "Whether the listed ProxyAdmins are EOAs, Safes or other contracts; signer threshold and recovery.",
    whyNow: "A newly live bounty and late-August update create a current security-design conversation around recently deployed cross-chain admin roles.",
    likelyBuyer: "Protocol engineering lead; chain/security lead",
    reachRoute: "GitHub contributors and official Discord; LinkedIn to protocol/chain engineering.",
    smartFirstQuestion: "Your deployment toolkit exposes dedicated ProxyAdmins on Base and Intuition. Is the same signer set used across chains, and what prevents one signer compromise from becoming a cross-chain upgrade event?",
    structuralSourceUrl: "https://github.com/0xIntuition/metalayer-token-deployment-toolkit",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/intuition/information/",
    fitScore: 29,
    triggerScore: 23,
    reachScore: 17,
    consequenceScore: 13,
    evidenceScore: 10,
    lockInPenalty: 2,
    score: 90,
    tier: "Tier 1",
    readiness: "Send now",
    outreachPosture: "Ask about cross-chain consistency; do not presume the recommended multisig was not used.",
  },
  {
    rank: 6,
    company: "Royco",
    segment: "Structured-yield protocol",
    chains: "Ethereum, Arbitrum, Base, Avalanche",
    triggerDate: "2026-08-12",
    datedTrigger: "Royco completed its Royco Day audit set on Aug 11 and updated the Immunefi program on Aug 12.",
    privilegedRole: "Upgradeable/pausable Market Syncer administered by protocol AccessManager; Pendle wrapper proxy uses Pendle ProxyAdmin/pause controller.",
    currentController: "AccessManager confirmed; human signer/key architecture behind it is unknown.",
    confirmedFact: "Royco\u2019s repository identifies an upgradeable, pausable singleton administered through its AccessManager.",
    inference: "AERSeal could protect the human/operational authority that controls AccessManager-sensitive changes.",
    unknown: "AccessManager admin address, signer threshold, timelock and recovery design.",
    whyNow: "A fresh audit and new periphery components make the admin-path design concrete and timely.",
    likelyBuyer: "Protocol lead; security lead; founder",
    reachRoute: "Royco GitHub/Discord and official contact; LinkedIn to protocol engineering.",
    smartFirstQuestion: "The Market Syncer is upgradeable and pausable through your AccessManager\u2014what ultimately controls that manager, and how are its signer keys generated and recovered?",
    structuralSourceUrl: "https://github.com/roycoprotocol/royco-day-periphery",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/royco/information/",
    fitScore: 27,
    triggerScore: 22,
    reachScore: 18,
    consequenceScore: 14,
    evidenceScore: 10,
    lockInPenalty: 2,
    score: 89,
    tier: "Tier 1",
    readiness: "Send now",
    outreachPosture: "Reference the exact Syncer/AccessManager path.",
  },
  {
    rank: 7,
    company: "NUVA",
    segment: "RWA vault marketplace",
    chains: "Ethereum",
    triggerDate: "2026-08-12",
    datedTrigger: "The May-launched bounty was updated in August after adding nvPRIME vault/router assets; the scope includes a named vault proxy.",
    privilegedRole: "Vault proxy upgrade/admin plus vault deposit/withdrawal administration.",
    currentController: "Proxy existence confirmed; controller type is unknown.",
    confirmedFact: "Immunefi lists the nvYLDS Vault Proxy and May-added nvPRIME vault/router contracts on Ethereum.",
    inference: "RWA vault operators may value threshold protection for upgrade and emergency authority as institutional exposure grows.",
    unknown: "ProxyAdmin owner, pause/guardian roles, signer identities and recovery.",
    whyNow: "A newly expanded RWA contract surface and fresh bug-bounty update create a specific pre-scale control review.",
    likelyBuyer: "Nuva Labs CTO; smart-contract/security lead",
    reachRoute: "Nuva Labs official contact/community; LinkedIn to engineering leadership.",
    smartFirstQuestion: "Your scope now includes the nvYLDS proxy and new nvPRIME vaults\u2014what address controls upgrades and emergency actions across those vaults today?",
    structuralSourceUrl: "https://immunefi.com/bug-bounty/nuva/scope/",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/nuva/information/",
    fitScore: 27,
    triggerScore: 21,
    reachScore: 18,
    consequenceScore: 13,
    evidenceScore: 9,
    lockInPenalty: 2,
    score: 86,
    tier: "Tier 1",
    readiness: "Validate then send",
    outreachPosture: "First verify the proxy owner on Etherscan.",
  },
  {
    rank: 8,
    company: "Strata",
    segment: "Synthetic assets / asset management",
    chains: "Ethereum",
    triggerDate: "2026-07-12",
    datedTrigger: "The public known-issues list documented a live implementation fix not yet deployed and separately identified a trusted UPDATER_FEED_ROLE.",
    privilegedRole: "UPDATER_FEED_ROLE; upgrade/pause capability for affected contracts.",
    currentController: "Role is confirmed; controller and signer design are unknown.",
    confirmedFact: "Immunefi describes a trusted updater role and says a repository fix was not deployed to live implementations.",
    inference: "AERSeal may protect updater and upgrade authority while the project expands into more strategies/RWAs.",
    unknown: "Role holder, whether updates use an EOA/multisig/timelock, and whether deployment has since changed.",
    whyNow: "A documented trusted role plus an undeployed implementation change creates a precise control-and-deployment discussion.",
    likelyBuyer: "Smart-contract lead; security lead; CTO",
    reachRoute: "Official docs/community and GitHub contributors; LinkedIn to protocol engineering.",
    smartFirstQuestion: "Who currently holds UPDATER_FEED_ROLE and the authority to deploy the pending implementation fix\u2014and are those two authorities deliberately separated?",
    structuralSourceUrl: "https://immunefi.com/bug-bounty/strata/information/",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/strata/information/",
    fitScore: 29,
    triggerScore: 18,
    reachScore: 16,
    consequenceScore: 15,
    evidenceScore: 10,
    lockInPenalty: 2,
    score: 86,
    tier: "Tier 1",
    readiness: "Validate then send",
    outreachPosture: "Verify whether the live fix was deployed after July 12.",
  },
  {
    rank: 9,
    company: "Olas (Autonolas)",
    segment: "Onchain AI services / DAO",
    chains: "Ethereum + 7 EVM chains",
    triggerDate: "2026-08-20",
    datedTrigger: "The bounty was updated after a 2026 Code4rena audit; living risk lists for governance, registries and tokenomics were refreshed in May.",
    privilegedRole: "GovernorOLAS + Timelock; proxy-upgradeable Tokenomics, staking, LiquidityManager, MechMarketplace and Karma contracts.",
    currentController: "Governance/timelock confirmed; signer layer for cross-chain guards/mediators remains unknown.",
    confirmedFact: "The current bounty scope explicitly identifies proxy-upgradeable components and cross-chain governance machinery.",
    inference: "AERSeal may complement governance by protecting emergency/cross-chain execution authorities across eight chains.",
    unknown: "Who controls proxy admins and guards, threshold design, and whether current controls are already equivalent.",
    whyNow: "The project recently consolidated audited governance and proxy scope across many EVM chains\u2014exactly when authority sprawl becomes operationally visible.",
    likelyBuyer: "Protocol/security lead; DAO governance steward",
    reachRoute: "Olas governance forum/Discord and GitHub maintainers; LinkedIn to protocol security.",
    smartFirstQuestion: "Across the proxy-upgradeable tokenomics, staking and marketplace components, is admin execution controlled by one cross-chain signer set or separated per domain?",
    structuralSourceUrl: "https://immunefi.com/bug-bounty/autonolas/information/",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/autonolas/information/",
    fitScore: 27,
    triggerScore: 21,
    reachScore: 17,
    consequenceScore: 12,
    evidenceScore: 10,
    lockInPenalty: 2,
    score: 85,
    tier: "Tier 1",
    readiness: "Send now",
    outreachPosture: "Position beneath governance, not as a governance replacement.",
  },
  {
    rank: 10,
    company: "Livepeer",
    segment: "Video/AI infrastructure network",
    chains: "Ethereum, Arbitrum",
    triggerDate: "2026-08-28",
    datedTrigger: "The bug-bounty scope was updated and explicitly calls out Governor-only functions, key theft and unauthorized transaction signing.",
    privilegedRole: "Governor-authorized contract calls and transaction signing.",
    currentController: "Governor contract is named; underlying execution/signing custody is unknown.",
    confirmedFact: "Current scope treats unexpected Governor-only calls, key theft and unauthorized signing as in-scope impacts.",
    inference: "AERSeal may protect the signer/executor beneath Governor-authorized operations.",
    unknown: "Governor executor, timelock, signer keys and recovery path.",
    whyNow: "A scope update this week makes privileged signing an explicit, current security concern.",
    likelyBuyer: "Protocol security lead; core protocol engineering",
    reachRoute: "Livepeer governance/community forum and GitHub; LinkedIn to core protocol security.",
    smartFirstQuestion: "Your updated scope explicitly covers Governor-only calls and unauthorized signing\u2014what key architecture sits behind the Governor\u2019s final execution path?",
    structuralSourceUrl: "https://immunefi.com/bug-bounty/livepeer/information/",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/livepeer/information/",
    fitScore: 28,
    triggerScore: 23,
    reachScore: 14,
    consequenceScore: 13,
    evidenceScore: 10,
    lockInPenalty: 4,
    score: 84,
    tier: "Tier 1",
    readiness: "Send now",
    outreachPosture: "Acknowledge Governor controls; ask about the final signer boundary.",
  },
  {
    rank: 11,
    company: "USDN / SmarDex",
    segment: "Synthetic dollar",
    chains: "Ethereum",
    triggerDate: "2026-07-24",
    datedTrigger: "The USDN Immunefi program was updated; it explicitly contemplates upgrade/pause mitigation for smart-contract incidents.",
    privilegedRole: "Upgrade and pause authority over synthetic-dollar contracts.",
    currentController: "Authority existence is indicated; exact controller is unknown.",
    confirmedFact: "The bounty\u2019s incident model says affected contracts may be upgraded or paused.",
    inference: "Stablecoin admin authority is a natural AERSeal surface if signer custody relies on complete keys.",
    unknown: "Which contracts are upgradeable/pausable, controller address, threshold, recovery and mint/burn role design.",
    whyNow: "A recent security-program update gives a legitimate reason to ask how emergency and upgrade authority is operated.",
    likelyBuyer: "SmarDex CTO; smart-contract/security lead",
    reachRoute: "SmarDex docs/community and GitHub; LinkedIn to core engineering.",
    smartFirstQuestion: "Which address currently holds USDN\u2019s upgrade and pause authority, and is mint/burn administration separated from that role?",
    structuralSourceUrl: "https://docs.smardex.io/ultimate-synthetic-delta-neutral",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/usdn/information/",
    fitScore: 26,
    triggerScore: 19,
    reachScore: 19,
    consequenceScore: 12,
    evidenceScore: 9,
    lockInPenalty: 1,
    score: 84,
    tier: "Tier 1",
    readiness: "Validate then send",
    outreachPosture: "Verify exact admin roles from deployed contracts first.",
  },
  {
    rank: 12,
    company: "MagpieXYZ",
    segment: "veToken yield / DAO",
    chains: "BNB Chain, Arbitrum, Ethereum",
    triggerDate: "2026-08-26",
    datedTrigger: "The multi-chain bug-bounty scope was updated; the page says more contracts will be added after an inactive product line was removed.",
    privilegedRole: "Governance/voting-power custody plus staking/yield contract administration.",
    currentController: "Unknown; role and signer architecture require contract-level verification.",
    confirmedFact: "Magpie accumulates ve-token governance power and operates Solidity contracts across three EVM chains.",
    inference: "Concentrated governance rights and multi-chain operations may create a privileged key-management use case.",
    unknown: "Exact admin roles, owners, thresholds and whether any contracts are immutable.",
    whyNow: "A scope refresh and upcoming contract additions create an opening before the next privileged surface goes live.",
    likelyBuyer: "Protocol lead; multisig/governance operations owner",
    reachRoute: "Official Discord/Telegram and GitHub; LinkedIn to protocol engineering.",
    smartFirstQuestion: "As you add the next contracts to scope, will the admin and emergency roles share today\u2019s signer set across BNB, Arbitrum and Ethereum?",
    structuralSourceUrl: "https://immunefi.com/bug-bounty/magpiexyz/information/",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/magpiexyz/information/",
    fitScore: 24,
    triggerScore: 23,
    reachScore: 18,
    consequenceScore: 12,
    evidenceScore: 8,
    lockInPenalty: 2,
    score: 83,
    tier: "Tier 1",
    readiness: "Research first",
    outreachPosture: "Do not send until one exact privileged role/controller is verified.",
  },
  {
    rank: 13,
    company: "Vesper",
    segment: "Yield aggregator",
    chains: "Ethereum",
    triggerDate: "2026-07-28",
    datedTrigger: "Vesper updated its Immunefi program while continuing to cover live pool contracts.",
    privilegedRole: "Pool/strategy upgrade and migration authority; multisig proposal workflow appears in deployment tooling.",
    currentController: "Multisig workflow indicated; current production signer setup is unknown.",
    confirmedFact: "The public contracts repository includes pool/accountant/reward upgrader deployment and multisig proposal tooling.",
    inference: "AERSeal may complement the existing multisig by removing complete signer-key exposure.",
    unknown: "Current repository/version, live upgrader owner, threshold and recovery.",
    whyNow: "A late-July scope update is a valid reason to re-check the current upgrade/migration control path.",
    likelyBuyer: "Protocol maintainer; security/operations lead",
    reachRoute: "Vesper community and current GitHub maintainers; LinkedIn to engineering.",
    smartFirstQuestion: "Your deployment tooling supports multisig-proposed pool upgrades\u2014how are the production signer keys protected and recovered today?",
    structuralSourceUrl: "https://github.com/vesperfi/vesper-pools",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/vesper/information/",
    fitScore: 25,
    triggerScore: 20,
    reachScore: 19,
    consequenceScore: 10,
    evidenceScore: 8,
    lockInPenalty: 1,
    score: 81,
    tier: "Tier 2",
    readiness: "Validate then send",
    outreachPosture: "Confirm the current repo and live owner before outreach.",
  },
  {
    rank: 14,
    company: "Twyne",
    segment: "Modular lending risk layer",
    chains: "Ethereum",
    triggerDate: "2026-06-25",
    datedTrigger: "Twyne updated its newly launched bounty and disclosed an upcoming upgrade for external liquidation-LTV changes.",
    privilegedRole: "Upgrade/pause authority over lending/risk components.",
    currentController: "Unknown.",
    confirmedFact: "The bounty states upgrade/pause can stop repeat attacks and says a specific upgrade is coming for an external-market change.",
    inference: "An upcoming upgrade is a good moment to review who can authorize and sign it.",
    unknown: "Proxy/admin address, owner type, threshold and recovery.",
    whyNow: "The team has publicly signaled an upcoming contract change and is small enough for direct technical outreach.",
    likelyBuyer: "Founder/CTO; smart-contract lead",
    reachRoute: "Twyne GitBook/community and GitHub maintainers; LinkedIn to founders.",
    smartFirstQuestion: "For the upcoming liquidation-LTV upgrade, what address authorizes the implementation change and how is that authority recovered if a signer is lost?",
    structuralSourceUrl: "https://immunefi.com/bug-bounty/twyne/information/",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/twyne/information/",
    fitScore: 25,
    triggerScore: 17,
    reachScore: 20,
    consequenceScore: 11,
    evidenceScore: 8,
    lockInPenalty: 1,
    score: 80,
    tier: "Tier 2",
    readiness: "Validate then send",
    outreachPosture: "Verify whether the announced upgrade has already shipped.",
  },
  {
    rank: 15,
    company: "Panoptic",
    segment: "Onchain options",
    chains: "Ethereum EVM",
    triggerDate: "2026-05-06",
    datedTrigger: "Panoptic completed its fourth/final V2 protocol audit; V2 and vault infrastructure were reviewed repeatedly in 2026.",
    privilegedRole: "Factory owner can update important deployed-pool parameters; protocol described as non-upgradeable in earlier audit.",
    currentController: "Owner role confirmed historically; current V2 owner/control model needs verification.",
    confirmedFact: "OpenZeppelin documented a privileged factory owner able to change maintenance margin, fees, collateral ratios and other pool parameters.",
    inference: "AERSeal could protect this non-upgrade admin parameter role if it remains in V2.",
    unknown: "Whether V2 retained the role, current owner type and signer architecture.",
    whyNow: "A final V2 audit marks the transition from design review toward operation\u2014a good time to verify the privileged parameter owner.",
    likelyBuyer: "Protocol lead; security lead; founder",
    reachRoute: "Panoptic developer/community channels and GitHub; LinkedIn to protocol engineering.",
    smartFirstQuestion: "Did V2 retain a factory-level parameter owner, and if so, what signer architecture now protects that role?",
    structuralSourceUrl: "https://www.openzeppelin.com/news/panoptic-audit",
    triggerSourceUrl: "https://panoptic.xyz/docs/security/security_audits",
    fitScore: 24,
    triggerScore: 18,
    reachScore: 18,
    consequenceScore: 11,
    evidenceScore: 9,
    lockInPenalty: 2,
    score: 78,
    tier: "Tier 2",
    readiness: "Validate then send",
    outreachPosture: "Confirm V2 role continuity; do not pitch upgrade protection if contracts are immutable.",
  },
  {
    rank: 16,
    company: "Silo Finance",
    segment: "Isolated lending + vaults",
    chains: "Ethereum",
    triggerDate: "2026-06-17",
    datedTrigger: "Silo updated the v2/v3 bounty as it operates programmable lending markets and managed vaults.",
    privilegedRole: "Upgrade/pause authority over lending/vault components.",
    currentController: "Unknown.",
    confirmedFact: "The current bounty treats upgrade/pause as available mitigation for at least some affected contracts.",
    inference: "Vault and market admin authority may be suitable for AERSeal if controlled by full signer keys.",
    unknown: "Exact proxy admin/guardian, signer threshold and recovery.",
    whyNow: "A v2/v3 scope refresh is a natural reason to ask whether the admin architecture also evolved.",
    likelyBuyer: "Smart-contract lead; security lead; DAO operations",
    reachRoute: "Silo governance/community and GitHub; LinkedIn to core protocol engineers.",
    smartFirstQuestion: "Across Silo v2 and v3, is upgrade/pause authority centralized in one controller or separated per market and vault family?",
    structuralSourceUrl: "https://github.com/silo-finance/silo-contracts-v3",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/silofinance-v2/information/",
    fitScore: 26,
    triggerScore: 15,
    reachScore: 16,
    consequenceScore: 14,
    evidenceScore: 9,
    lockInPenalty: 3,
    score: 77,
    tier: "Tier 2",
    readiness: "Research first",
    outreachPosture: "Map exact owners in the official deployment registry before sending.",
  },
  {
    rank: 17,
    company: "Velodrome Finance",
    segment: "AMM / DEX",
    chains: "Optimism",
    triggerDate: "2026-07-05",
    datedTrigger: "Velodrome updated its security program, which recognizes upgrade/pause/kill responses for some contracts.",
    privilegedRole: "Upgrade, pause or kill authority for parts of the protocol.",
    currentController: "Unknown from current public source.",
    confirmedFact: "The bounty explicitly distinguishes contracts that can be upgraded, paused or killed from immutable contracts.",
    inference: "The privileged contracts could fit AERSeal if their controller uses complete signer keys.",
    unknown: "Which current contracts are mutable, owner addresses, signer threshold and governance execution path.",
    whyNow: "A recent bounty update provides a current entry point, but admin mapping is required before outreach.",
    likelyBuyer: "Protocol/security lead; governance operations",
    reachRoute: "Velodrome governance/community and GitHub; LinkedIn to core contributors.",
    smartFirstQuestion: "Which current Velodrome components still have upgrade, pause or kill authority, and what controls those roles after governance approval?",
    structuralSourceUrl: "https://github.com/velodrome-finance/contracts",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/velodromefinance/information/",
    fitScore: 25,
    triggerScore: 16,
    reachScore: 17,
    consequenceScore: 13,
    evidenceScore: 9,
    lockInPenalty: 3,
    score: 77,
    tier: "Tier 2",
    readiness: "Research first",
    outreachPosture: "Do not assume the central AMM contracts are upgradeable.",
  },
  {
    rank: 18,
    company: "dHEDGE",
    segment: "Onchain asset management",
    chains: "Ethereum, Arbitrum, Base, Optimism, Polygon",
    triggerDate: "2026-02-17",
    datedTrigger: "The multi-chain bounty was updated for the current asset-management system; the scope recognizes upgrade/pause incident response.",
    privilegedRole: "Upgrade/pause plus contract-guard and asset-guard administration.",
    currentController: "Unknown.",
    confirmedFact: "dHEDGE operates multi-chain Solidity asset-management contracts; current bounty includes guard integrations and upgrade/pause mitigation.",
    inference: "Guard administration across several chains can create concentrated privileged authority.",
    unknown: "Current admin/owner addresses, signer sets and timelock design.",
    whyNow: "This is a smaller, reachable team, but the trigger is older; monitor for the next deployment or guard change before sending unless a role is verified now.",
    likelyBuyer: "Protocol engineering lead; security owner",
    reachRoute: "dHEDGE developer/community channels and GitHub; LinkedIn to engineers.",
    smartFirstQuestion: "Are contract-guard and asset-guard changes controlled by the same signer set across all five EVM deployments?",
    structuralSourceUrl: "https://github.com/dhedge/V2-Public",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/dhedge/information/",
    fitScore: 24,
    triggerScore: 14,
    reachScore: 19,
    consequenceScore: 11,
    evidenceScore: 8,
    lockInPenalty: 1,
    score: 75,
    tier: "Tier 2",
    readiness: "Monitor",
    outreachPosture: "Wait for a fresher deployment/governance trigger unless a direct role gap is verified.",
  },
  {
    rank: 19,
    company: "Tetu",
    segment: "Yield aggregator / asset management",
    chains: "Polygon",
    triggerDate: "2026-06-08",
    datedTrigger: "Tetu refreshed its small $2k bounty, including governance disruption and governance-fund impacts.",
    privilegedRole: "Governance and strategy/vault administration; exact role mapping is not public in the cited page.",
    currentController: "Unknown.",
    confirmedFact: "Live Polygon Solidity protocol with explicit governance security impacts and a very small bounty, indicating a compact team.",
    inference: "Its size may make direct founder/maintainer access easier, but budget and authority fit require confirmation.",
    unknown: "Material value, admin roles, owner addresses, signer design and purchasing budget.",
    whyNow: "Security activity is recent and reachability is high; qualify budget and live value before proposing a pilot.",
    likelyBuyer: "Core maintainer; multisig/governance operator",
    reachRoute: "Tetu community/GitHub; direct maintainer LinkedIn.",
    smartFirstQuestion: "What address currently controls strategy upgrades and emergency actions, and is that separate from the treasury multisig?",
    structuralSourceUrl: "https://immunefi.com/bug-bounty/tetu/information/",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/tetu/information/",
    fitScore: 23,
    triggerScore: 14,
    reachScore: 20,
    consequenceScore: 8,
    evidenceScore: 7,
    lockInPenalty: 0,
    score: 72,
    tier: "Tier 2",
    readiness: "Research first",
    outreachPosture: "Qualify budget and value secured before outreach.",
  },
  {
    rank: 20,
    company: "GammaSwap",
    segment: "AMM liquidity borrowing / derivatives",
    chains: "Arbitrum",
    triggerDate: "2026-05-19",
    datedTrigger: "GammaSwap refreshed its $40k bug-bounty program for the Arbitrum protocol.",
    privilegedRole: "Likely parameter/admin authority around pool factories and interest models; exact privileged role not yet verified.",
    currentController: "Unknown.",
    confirmedFact: "Active Solidity protocol and bounty; public core-contract repository exists.",
    inference: "Factory or parameter administration may fit AERSeal.",
    unknown: "Whether production contracts are mutable, exact admin roles, controller and value secured.",
    whyNow: "Reachable team and recent security attention, but this is a research candidate\u2014not send-ready.",
    likelyBuyer: "Founder/CTO; smart-contract lead",
    reachRoute: "GammaSwap community and GitHub contributors; LinkedIn to founders/engineering.",
    smartFirstQuestion: "Which production roles can change pool, fee or interest-model configuration, and are any of them held outside onchain governance?",
    structuralSourceUrl: "https://github.com/gammaswap/v1-core",
    triggerSourceUrl: "https://immunefi.com/bug-bounty/gammaswap/information/",
    fitScore: 23,
    triggerScore: 12,
    reachScore: 19,
    consequenceScore: 10,
    evidenceScore: 8,
    lockInPenalty: 1,
    score: 71,
    tier: "Research",
    readiness: "Research first",
    outreachPosture: "Do not contact until one privileged function is confirmed.",
  },
]
