// ============================================================
// TypeScript Types for Kima BD OS
// ============================================================

export type LeadStatus =
  | 'new'
  | 'researching'
  | 'qualified'
  | 'approved'
  | 'rejected'
  | 'contacted'
  | 'replied'
  | 'meeting_booked'
  | 'proposal_sent'
  | 'negotiating'
  | 'integration'
  | 'won'
  | 'lost'
  | 'archived'
  | 'needs_more_research'
  | 'reserved'

export type LeadPriority = 'excellent' | 'qualified' | 'needs_research' | 'low_priority'

export type PainPointSeverity = 'critical' | 'high' | 'medium' | 'low'

export type ContactConfidence = 'high' | 'medium' | 'low' | 'unknown'

export type SourceType =
  | 'website'
  | 'google_search'
  | 'twitter_profile'
  | 'linkedin_company'
  | 'telegram_group'
  | 'rss_feed'
  | 'defillama_category'
  | 'crunchbase_list'
  | 'ecosystem_directory'
  | 'hackathon_directory'
  | 'news_source'
  | 'manual_list'
  | 'apollo_search'
  | 'exa_search'
  | 'exa_similar'

export type OutreachChannel = 'telegram' | 'linkedin' | 'twitter' | 'email'

export type OutreachTone =
  | 'casual'
  | 'professional'
  | 'founder_to_founder'
  | 'concise'
  | 'strong_bd'

export type RuleType =
  | 'prioritize'
  | 'reject'
  | 'score_boost'
  | 'score_penalty'
  | 'outreach_style'
  | 'source_preference'

export type FeedbackAction =
  | 'approved'
  | 'rejected'
  | 'edited'
  | 'contacted'
  | 'replied'
  | 'meeting_booked'
  | 'deal_closed'
  | 'needs_more_research'

export const INDUSTRY_CATEGORIES = [
  'Cross-border payment company',
  'PSP/payment gateway',
  'On/off-ramp provider',
  'Stablecoin payment company',
  'Wallet',
  'DEX',
  'Perp DEX',
  'Launchpad',
  'RWA platform',
  'iGaming/payment-heavy platform',
  'Neobank',
  'Fintech',
  'Exchange',
  'Chain ecosystem',
  'AI commerce/payment agent',
  'Treasury management platform',
  'Custody/payment infrastructure company',
  'Web2 company with payment/settlement friction',
  'Other',
] as const

export const CUSTOMER_CATEGORIES = [
  'Agentic Payments Customer',
  'Aerpolice Governance Customer',
  'AERKey / Key Governance Customer',
  'LayerZero Customer',
  'Hacked Protocol',
  'Needs On/Off Ramp',
  'Fireblocks Customer',
  'Web2 Stablecoin Settlement Customer',
  'Other',
] as const

export const PRODUCTS_TO_SELL = [
  'Agentic payment rails',
  'Aerpolice agent governance',
  'AERKey threshold signing',
  'Cross-chain settlement',
  'Stablecoin settlement',
  'Fiat on/off-ramp',
  'Treasury movement',
  'DvP settlement',
  'iGaming payments',
  'RWA settlement',
  'PSP settlement',
  'Wallet onboarding',
  'Launchpad participation',
  'Payment orchestration',
  'Cross-border USDT/USDC settlement',
] as const

export const REGIONS = [
  'Global',
  'North America',
  'Europe',
  'Asia',
  'Middle East',
  'Africa',
  'Southeast Asia',
  'South Asia',
  'Latin America',
  'MENA',
  'EU-India corridor',
  'UAE-India corridor',
  'US-India corridor',
] as const

export type IndustryCategory = (typeof INDUSTRY_CATEGORIES)[number]
export type CustomerCategory = (typeof CUSTOMER_CATEGORIES)[number]
export type ProductToSell = (typeof PRODUCTS_TO_SELL)[number]
export type Region = (typeof REGIONS)[number]

// ── BD Brief ───────────────────────────────────────────────────
// Generated by /api/ai/bd-brief — the quick-scan 7-section brief
// designed to answer "is this worth pursuing?" in 30-60 seconds.
export interface BDBrief {
  lead_summary:         string[]    // 2-3 bullet points, plain English
  how_money_moves:      string      // short paragraph on fund/value flow
  pain_points:          string[]    // top 3 operational problems
  opportunity: {
    products:           string[]    // ["Kima", "Aeredium", "Aerpolice"] — only what applies
    gap_solved:         string      // one sentence
    why_they_care:      string      // one sentence on business outcome
  }
  real_use_case: {
    title:              string
    scenario:           string      // the setup: who operates what system
    trigger:            string      // the EXACT triggering event (with numbers/thresholds)
    decision:           string      // what the system/agent decides to do
    workflow:           string[]    // concrete numbered steps: what moved, from where, to where, through which infra
    products_used:      UseCaseProduct[]  // which products, which exact features, why each matters
    without_us:         string      // what concretely happens today without us (the failure mode)
    business_outcome:   string      // measurable result
  }
  discovery_questions:  string[]    // 3-5 real call questions
  bd_verdict: {
    fit:                'Strong Fit' | 'Moderate Fit' | 'Weak Fit'
    reason:             string      // one sentence
  }
}

// Which product + which exact features + WHY each feature matters.
// This is what makes a use case operationally believable rather than abstract.
export interface UseCaseProduct {
  product: 'Kima' | 'Aeredium' | 'Aerpolice'
  features: string[]   // exact capabilities used (e.g. "Atomic settlement", "MPC custody")
  why: string          // why each feature is necessary for THIS company's situation
}

export interface UseCase {
  id: string
  title: string
  category: string

  // ── Operationally-concrete structure (Trigger → Decision → Workflow → Products → Outcome) ──
  scenario?: string | string[]      // the setup: who operates what system
  trigger?: string                  // the EXACT triggering event (threshold/time/condition, with numbers)
  decision?: string                 // what the system/agent decides to do as a result
  workflow?: string[]               // concrete numbered steps — what moved, from where, to where, through which infra
  products_used?: UseCaseProduct[]  // which products, which exact features, why each matters
  without_us?: string               // what concretely happens today without our product (the failure mode)
  business_outcome?: string         // the measurable result

  // ── Legacy fields (kept so older saved use cases still render) ──
  kima_role?: string | string[]
  aeredium_role?: string | string[]
  pain_point_proof?: string | string[]
  our_products_used?: string[]
  outcome_for_company?: string | string[]
  outcome_for_kima?: string | string[]

  feasibility: 'high' | 'medium' | 'low'
  impact: 'transformative' | 'significant' | 'incremental'
  why_now?: string
}

// ── Per-product fit matrix ────────────────────────────────────────
// One entry per product in the full 9-product catalog (Kima UPR/LaaS/DvP,
// Aeredium L1/AERLink/AERKey, Aerpolice Identity/Gate/Audit). Lets a lead
// point at the specific best-fit product (e.g. AERKey) rather than only a
// company-level fit (kima_fit / aeredium_fit / aerpolice_fit).
export interface ProductMatch {
  product: string
  company: 'Kima' | 'Aeredium' | 'Aerpolice'
  match: 'strong' | 'partial' | 'none'
  why: string
  use_case?: string
}

export interface Lead {
  id: string
  company_name: string
  website?: string
  industry_category?: string
  customer_category?: string[]
  product_to_sell?: string
  region?: string
  description?: string
  business_model?: string
  product_summary?: string
  supported_chains_or_rails?: string
  current_providers?: string
  competitor_or_current_provider?: string
  competitor_context?: string
  pain_point?: string
  pain_point_severity?: PainPointSeverity
  pain_point_evidence?: string
  pain_point_source_url?: string
  pain_point_evidence_type?: 'verified_source' | 'agent_analysis' | 'inferred'
  kima_fit?: string
  aeredium_fit?: string
  aerpolice_fit?: string
  agent_control_angle?: string
  product_matches?: ProductMatch[]
  suggested_use_case?: string
  trigger_reason?: string
  risk_angle?: string
  settlement_angle?: string
  security_angle?: string
  revenue_potential?: string
  integration_feasibility?: string
  source_url?: string
  source_summary?: string
  twitter_url?: string
  telegram_url?: string
  discord_url?: string
  facts?: Record<string, unknown>[]
  assumptions?: Record<string, unknown>[]
  use_cases?: UseCase[]
  bd_brief?: BDBrief
  lead_score?: number
  confidence_score?: number
  priority?: LeadPriority
  status: LeadStatus
  contacted_at?: string
  last_contacted_at?: string
  follow_up_stage?: number
  next_follow_up_at?: string
  last_channel?: string
  assigned_to?: string | null
  created_at: string
  updated_at: string
  contacts?: Contact[]
  outreach_messages?: OutreachMessage[]
  contacts_total?: number     // total contacts found at this company
  contacts_reached?: number   // how many have been actually contacted
}

export interface ContactTouch {
  channel: string
  contacted_at: string
  note?: string
}

export interface Contact {
  id: string
  lead_id: string
  name?: string
  role?: string
  company?: string
  linkedin_url?: string
  twitter_url?: string
  github_url?: string
  telegram?: string
  email?: string
  contact_confidence?: ContactConfidence
  reason_this_person?: string
  source_url?: string
  contacted_channels?: ContactTouch[]
  created_at: string
}

export interface OutreachMessage {
  id: string
  lead_id: string
  contact_id?: string
  channel?: OutreachChannel
  tone?: OutreachTone
  customer_category?: string
  product_to_sell?: string
  message?: string
  followup_1?: string
  followup_2?: string
  objection_reply?: string
  call_opening?: string
  meeting_agenda?: string
  status: 'draft' | 'sent' | 'delivered' | 'replied' | 'archived'
  created_at: string
  updated_at: string
}

export interface Source {
  id: string
  source_name: string
  source_type?: SourceType
  source_url_or_query?: string
  target_industry_category?: string
  target_customer_category?: string
  frequency?: 'daily' | 'weekly' | 'manual'
  quality_rating?: 'excellent' | 'good' | 'average' | 'poor' | 'unrated'
  status: 'active' | 'paused'
  notes?: string
  last_run_at?: string
  leads_generated?: number
  created_at: string
  updated_at: string
}

export interface FeedbackMemory {
  id: string
  lead_id: string
  contact_id?: string
  outreach_id?: string
  action_taken?: FeedbackAction
  lead_quality?: 'excellent' | 'good' | 'average' | 'poor'
  pain_point_accuracy?: 'very_accurate' | 'mostly_accurate' | 'partially_accurate' | 'inaccurate'
  contact_accuracy?: 'perfect' | 'good' | 'off' | 'wrong'
  message_quality?: 'excellent' | 'good' | 'needs_work' | 'poor'
  outcome?: 'replied' | 'meeting_booked' | 'deal_in_progress' | 'deal_closed' | 'no_response' | 'rejected_by_prospect' | 'not_yet_sent'
  rejection_reason?: string
  arpit_notes?: string
  created_at: string
  lead?: Lead
}

export interface AgentRule {
  id: string
  rule_type?: RuleType
  rule: string
  weight: number
  status: 'active' | 'inactive' | 'pending_approval'
  suggestion_reason?: string   // set when status = 'pending_approval'
  created_at: string
  updated_at: string
}

export interface LearningReport {
  id: string
  report_period?: string
  summary?: string
  winning_patterns?: Record<string, unknown>[]
  rejected_patterns?: Record<string, unknown>[]
  best_sources?: Record<string, unknown>[]
  worst_sources?: Record<string, unknown>[]
  best_customer_categories?: Record<string, unknown>[]
  worst_customer_categories?: Record<string, unknown>[]
  best_products_to_sell?: Record<string, unknown>[]
  scoring_changes_suggested?: Record<string, unknown>[]
  outreach_changes_suggested?: Record<string, unknown>[]
  new_rules_suggested?: Record<string, unknown>[]
  status: 'pending_review' | 'approved' | 'archived'
  created_at: string
}

export interface AgentKnowledge {
  id: string
  title: string
  content: string
  source_type?: 'file' | 'url' | 'text' | 'image' | 'screenshot'
  source_name?: string
  tags?: string[]
  rules_created?: number
  sources_created?: number
  knowledge_type?: string
  status: 'active' | 'archived'
  created_at: string
}

// Scoring system
export interface ScoreBreakdown {
  pain_point_score: number
  traction_score: number
  contact_score: number
  trigger_score: number
  category_fit_score: number
  integration_feasibility_score: number
  revenue_potential_score: number
  category_boost: number
  penalties: number
  total: number
  priority: LeadPriority
}

// ── Custom Products (AI-researched) ──────────────────────────────
// Generated by /api/ai/product-research — the user pastes a URL, uploads a
// document, or pastes text describing a product/service; the agent
// researches it and returns this structured BD go-to-market analysis.
export interface CustomProductAnalysis {
  layman_explanation: string        // 2-4 sentences, no jargon — "explain like I'm not technical"
  market_fit: {
    verdict:   'Strong Fit' | 'Moderate Fit' | 'Weak Fit' | 'Not a Fit'
    reasoning: string[]             // 3-5 bullets backing the verdict, grounded in the source content
  }
  use_cases:  string[]              // concrete real-life scenarios, not generic statements
  gap_filled: string[]              // what's broken/missing/painful today that this solves
  icp: {
    description: string             // 1-2 sentence ICP summary
    segments:    string[]           // concrete customer segments/personas
  }
  where_to_find_customers:   string[]  // channels, directories, communities, events, search queries
  fastest_closing_segments: {
    segment: string
    why:     string                 // why this segment has a short sales cycle
  }[]
  sources?: string[]                // citation URLs, if live web research was used
}

export interface CustomProduct {
  id:               string
  name:             string
  source_type:      'url' | 'document' | 'text'
  source_url:       string | null
  source_filename:  string | null
  analysis:         CustomProductAnalysis
  status:           'active' | 'archived'
  created_at:       string
}
